/**
 * Copyright 2020-2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * \file aoc-interface.h
 *
 * Autogenerated AoC interface matching AoC source code
 * associated with the following source code:
 *
 *   hash: f31773bd7eb20b955552679f755f9aac24c75bea
 *
 * DO NOT MODIFY THIS FILE
 *
 */

#ifndef AOC_INTERFACE_H_
#define AOC_INTERFACE_H_


#ifdef __KERNEL__
  #include <linux/kernel.h>
#else
  #include <stdint.h>
#endif


/**
 * System timer tick [hz].  All time counts will be based on tick running at this frequency.
 *
 * UUID: 6ff8a9e0249904d2059bb069dfcd5357
 */
#define AOC_TIMER_FREQUENCY 4096000


/**
 * List of supported commands.
 */
enum AOC_COMMAND {
  CMD_RING_BIND_ID = 5, /* ->  struct CMD_RING_BIND */
  CMD_SYS_VERSION_GET_ID = 6, /* ->  struct CMD_SYS_VERSION_GET */
  CMD_SYS_BANNER_ID = 7, /* ->  struct CMD_CORE_GENERIC */
  CMD_SYS_STATS_TOT_ID = 8, /* ->  struct CMD_SYS_STATS_TOT */
  CMD_SYS_STATS_INFO_GET_ID = 9, /* ->  struct CMD_SYS_STATS_INFO_GET */
  CMD_SYS_STATS_TIMED_GET_ID = 10, /* ->  struct CMD_SYS_STATS_TIMED_GET */
  CMD_SYS_STATS_DATA_GET_ID = 11, /* ->  struct CMD_SYS_STATS_DATA_GET */
  CMD_SYS_STATS_ID = 12, /* ->  struct CMD_CORE_GENERIC */
  CMD_SYS_LOGIC_TRACE_ENABLE_ID = 13, /* ->  struct CMD_ENABLE */
  CMD_SYS_LOGIC_TRACE_SCHEME_SET_ID = 14, /* ->  struct CMD_CORE_LOGIC_TRACE_SCHEME */
  CMD_SYS_LOGIC_TRACE_SCHEME_GET_ID = 15, /* ->  struct CMD_CORE_LOGIC_TRACE_SCHEME */
  CMD_DBG_WATCHDOG_TRIGGER_ID = 16, /* ->  struct CMD_CORE_GENERIC */
  CMD_DBG_TREE_ID = 17, /* ->  struct CMD_CORE_GENERIC */
  CMD_DBG_INFO_ID = 18, /* ->  struct CMD_DBG_INFO */
  CMD_DBG_HEAP_ID = 19, /* ->  struct CMD_DBG_HEAP */
  CMD_DBG_LEVEL_GET_ID = 21, /* ->  struct CMD_DBG_LEVEL_GET */
  CMD_DBG_CONTROLLERS_ID = 22, /* ->  struct CMD_CORE_GENERIC */
  CMD_DBG_FILTERS_ID = 23, /* ->  struct CMD_CORE_GENERIC */
  CMD_DBG_PIPES_ID = 24, /* ->  struct CMD_CORE_GENERIC */
  CMD_DBG_POOLS_ID = 25, /* ->  struct CMD_CORE_GENERIC */
  CMD_DBG_RINGS_ID = 26, /* ->  struct CMD_CORE_GENERIC */
  CMD_DBG_IPCS_ID = 27, /* ->  struct CMD_CORE_GENERIC */
  CMD_DBG_FSM_ID = 28, /* ->  struct CMD_CORE_GENERIC */
  CMD_DBG_TASKS_ID = 29, /* ->  struct CMD_CORE_GENERIC */
  CMD_DBG_POWERMAN_ID = 30, /* ->  struct CMD_DBG_POWERMAN */
  CMD_DBG_TIMER_ID = 31, /* ->  struct CMD_CORE_GENERIC */
  CMD_DBG_LOG_ID = 32, /* ->  struct CMD_DBG_LOG */
  CMD_DBG_TIMESTAMP_ID = 33, /* ->  struct CMD_ENABLE */
  CMD_DBG_INTCNTRL_ID = 34, /* ->  struct CMD_CORE_GENERIC */
  CMD_DBG_IPC_SPACES_ID = 35, /* ->  struct CMD_CORE_GENERIC */
  CMD_DBG_IPC_CHANNELS_ID = 36, /* ->  struct CMD_CORE_GENERIC */
  CMD_DBG_MEM_SET_ID = 37, /* ->  struct CMD_DBG_MEM_SET */
  CMD_DBG_MEM_DUMP_ID = 38, /* ->  struct CMD_DBG_MEM_DUMP */
  CMD_IPC_NOTIF_ENABLE_ID = 39, /* ->  struct CMD_IPC_NOTIF_ENABLE */
  CMD_AUDIO_OUTPUT_SINK_ID = 40, /* ->  struct CMD_AUDIO_OUTPUT_SINK */
  CMD_AUDIO_OUTPUT_SOURCE_ID = 41, /* ->  struct CMD_AUDIO_OUTPUT_SOURCE */
  CMD_AUDIO_OUTPUT_BIND_ID = 42, /* ->  struct CMD_AUDIO_OUTPUT_BIND */
  CMD_AUDIO_INPUT_MIC_POWER_ON_ID = 43, /* ->  struct CMD_AUDIO_INPUT_MIC_POWER_ON */
  CMD_AUDIO_OUTPUT_WAV_PLAYBACK_ID = 43, /* ->  struct CMD_AUDIO_OUTPUT_WAV_PLAYBACK */
  CMD_AUDIO_INPUT_MIC_POWER_OFF_ID = 44, /* ->  struct CMD_AUDIO_INPUT_MIC_POWER_OFF */
  CMD_AUDIO_OUTPUT_GAIN_ID = 44, /* ->  struct CMD_AUDIO_OUTPUT_GAIN */
  CMD_AUDIO_INPUT_MIC_GET_POWER_STATE_ID = 45, /* ->  struct CMD_AUDIO_INPUT_MIC_GET_POWER_STATE */
  CMD_AUDIO_OUTPUT_FX_EQ_ID = 45, /* ->  struct CMD_AUDIO_OUTPUT_FX_EQ */
  CMD_AUDIO_INPUT_HOTWORD_ENABLE_AEC_ID = 46, /* ->  struct CMD_HDR */
  CMD_AUDIO_OUTPUT_EP_SETUP_ID = 46, /* ->  struct CMD_AUDIO_OUTPUT_EP_SETUP */
  CMD_AUDIO_INPUT_HOTWORD_DISABLE_AEC_ID = 47, /* ->  struct CMD_HDR */
  CMD_AUDIO_OUTPUT_DECODE_ID = 47, /* ->  struct CMD_AUDIO_OUTPUT_DECODE */
  CMD_AUDIO_OUTPUT_AEC_NOTIFY_ID = 48, /* ->  struct CMD_AUDIO_OUTPUT_AEC_NOTIFY */
  CMD_AUDIO_OUTPUT_SET_PARAMETER_ID = 49, /* ->  struct CMD_AUDIO_OUTPUT_SET_PARAMETER */
  CMD_AUDIO_INPUT_MODEM_INPUT_START_ID = 50, /* ->  struct CMD_HDR */
  CMD_AUDIO_OUTPUT_SET_PARAMETER_BULK_ID = 50, /* ->  struct CMD_AUDIO_OUTPUT_SET_PARAMETER_BULK */
  CMD_AUDIO_INPUT_MODEM_INPUT_STOP_ID = 51, /* ->  struct CMD_HDR */
  CMD_AUDIO_OUTPUT_GET_PARAMETER_ID = 51, /* ->  struct CMD_AUDIO_OUTPUT_GET_PARAMETER */
  CMD_AUDIO_OUTPUT_GET_PARAMETER_BULK_ID = 52, /* ->  struct CMD_AUDIO_OUTPUT_GET_PARAMETER_BULK */
  CMD_AUDIO_OUTPUT_SET_GET_PARAM_BULK_ID = 53, /* ->  struct CMD_AUDIO_OUTPUT_SET_GET_PARAM_BULK */
  CMD_AUDIO_INPUT_BT_CAPTURE_START_ID = 54, /* ->  struct CMD_HDR */
  CMD_AUDIO_OUTPUT_RESYNC_AUDIO_SINK_ID = 54, /* ->  struct CMD_AUDIO_OUTPUT_RESYNC_AUDIO_SINK */
  CMD_AUDIO_INPUT_BT_CAPTURE_STOP_ID = 55, /* ->  struct CMD_HDR */
  CMD_AUDIO_INPUT_BT_DECODER_START_ID = 56, /* ->  struct CMD_HDR */
  CMD_AUDIO_INPUT_BT_DECODER_STOP_ID = 57, /* ->  struct CMD_HDR */
  CMD_AUDIO_INPUT_BT_DECODER_ENABLE_OUTPUT_ID = 58, /* ->  struct CMD_AUDIO_INPUT_BT_ENABLE_OUTPUT */
  CMD_AUDIO_INPUT_BT_DECODER_DISABLE_OUTPUT_ID = 59, /* ->  struct CMD_AUDIO_INPUT_BT_DISABLE_OUTPUT */
  CMD_AUDIO_INPUT_IN_CALL_SELECT_START_ID = 60, /* ->  struct CMD_HDR */
  CMD_AUDIO_INPUT_IN_CALL_SELECT_STOP_ID = 61, /* ->  struct CMD_HDR */
  CMD_AUDIO_INPUT_IN_CALL_SELECT_ENABLE_OUTPUT_ID = 62, /* ->  struct CMD_AUDIO_INPUT_IN_CALL_SELECT_ENABLE_OUTPUT */
  CMD_AUDIO_INPUT_IN_CALL_SELECT_DISABLE_OUTPUT_ID = 63, /* ->  struct CMD_AUDIO_INPUT_IN_CALL_SELECT_DISABLE_OUTPUT */
  CMD_AUDIO_INPUT_MIC_RECORD_AP_SET_PARAMS_ID = 64, /* ->  struct CMD_AUDIO_INPUT_MIC_RECORD_AP_SET_PARAMS */
  CMD_AUDIO_OUTPUT_CFG_HAPTICS_ID = 64, /* ->  struct CMD_AUDIO_OUTPUT_CFG_HAPTICS */
  CMD_AUDIO_INPUT_MIC_RECORD_AP_START_ID = 65, /* ->  struct CMD_HDR */
  CMD_AUDIO_OUTPUT_CFG_SIGGEN_ID = 65, /* ->  struct CMD_AUDIO_OUTPUT_CFG_SIGGEN */
  CMD_AUDIO_INPUT_MIC_RECORD_AP_STOP_ID = 66, /* ->  struct CMD_HDR */
  CMD_AUDIO_INPUT_HOTWORD_START_ID = 67, /* ->  struct CMD_HDR */
  CMD_AUDIO_INPUT_HOTWORD_STOP_ID = 68, /* ->  struct CMD_HDR */
  CMD_AUDIO_INPUT_MIC_LOOPBACK_START_ID = 69, /* ->  struct CMD_AUDIO_INPUT_ENABLE_MIC_LOOPBACK */
  CMD_AUDIO_INPUT_MIC_LOOPBACK_STOP_ID = 70, /* ->  struct CMD_HDR */
};

/**
 * List of available notifications.
 */
enum AOC_NOTIFICATION {
  NOTIF_AUDIO_INPUT_AP_MIC_RECORD_DATA_AVAILABLE_ID = 2, /* ->  struct NOTIF */
};

enum DATA_TYPE {
  DATA_TYPE_CMD = 0,
  DATA_TYPE_NOTIF,
  DATA_TYPE_SIGNAL,
  DATA_TYPE_MSG,
};

struct CONTAINER_HDR {
  uint8_t type; /* For valid values, refer to "enum DATA_TYPE" */
  uint8_t cntr;
  uint16_t len;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_INPUT_HOTWORD_ENABLE_AEC_ID, UUID: 18fdab46301e622574da7ebf4ccc4663
 *   CMD_AUDIO_INPUT_HOTWORD_DISABLE_AEC_ID, UUID: aaf5479b1be98e8b7c8df22fe2f576de
 *   CMD_AUDIO_INPUT_MODEM_INPUT_START_ID, UUID: e40c4152fcde65b6663f1c58b87f2678
 *   CMD_AUDIO_INPUT_MODEM_INPUT_STOP_ID, UUID: be650fd5ee17044603deb365080f5ead
 *   CMD_AUDIO_INPUT_BT_CAPTURE_START_ID, UUID: 53f2efdb44af39df1b3242600b9c8202
 *   CMD_AUDIO_INPUT_BT_CAPTURE_STOP_ID, UUID: f7d9f172247fe127af5986ed9d9c3586
 *   CMD_AUDIO_INPUT_BT_DECODER_START_ID, UUID: 577174a2ce333a46f68e04470ccbb967
 *   CMD_AUDIO_INPUT_BT_DECODER_STOP_ID, UUID: 41a3b7899491b19c0d328993705aede1
 *   CMD_AUDIO_INPUT_IN_CALL_SELECT_START_ID, UUID: 727c13b0f20d9557a66e2c58113dfcf4
 *   CMD_AUDIO_INPUT_IN_CALL_SELECT_STOP_ID, UUID: 5cc69df12d2fe96074e0bf7f4af653c9
 *   CMD_AUDIO_INPUT_MIC_RECORD_AP_START_ID, UUID: 11bcb486e7e12241b0396d6c66caf42d
 *   CMD_AUDIO_INPUT_MIC_RECORD_AP_STOP_ID, UUID: 3e92cd4cb4cdb86f8e0816054bf05ad9
 *   CMD_AUDIO_INPUT_HOTWORD_START_ID, UUID: ee9847de96d939cf407616db9ed02d35
 *   CMD_AUDIO_INPUT_HOTWORD_STOP_ID, UUID: 38606bfc607b5bf1a216ca1277ff738f
 *   CMD_AUDIO_INPUT_MIC_LOOPBACK_STOP_ID, UUID: 44879fb7901d8570993514a38d790e35
 */
struct CMD_HDR {
  struct CONTAINER_HDR parent;
  uint16_t id;
  int16_t reply;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_SYS_BANNER_ID, UUID: 7f3783aedbae03854d3cb2851aa07b40
 *   CMD_SYS_STATS_ID, UUID: 6dafca1b50ff4f7aacc4006c0e104b7e
 *   CMD_DBG_WATCHDOG_TRIGGER_ID, UUID: 2fad4cb475c496c9f76c32dca4c0136a
 *   CMD_DBG_TREE_ID, UUID: da949c27a8bc2dc785655f91075aca1a
 *   CMD_DBG_CONTROLLERS_ID, UUID: 71bc548e4d11016c86ef267c16a161d9
 *   CMD_DBG_FILTERS_ID, UUID: 63cb8f092494b957fcd93039d904613f
 *   CMD_DBG_PIPES_ID, UUID: d3a52cad717826918f484ef64874d181
 *   CMD_DBG_POOLS_ID, UUID: d1c958027b2ed6f8a4bfab4e29deb01f
 *   CMD_DBG_RINGS_ID, UUID: 26ff9e044e65510775291abe87405fbc
 *   CMD_DBG_IPCS_ID, UUID: 7b9075e0318eba314f60f62fe53cda03
 *   CMD_DBG_FSM_ID, UUID: b082cbc3dd47affcbed81f2f6a8bdc26
 *   CMD_DBG_TASKS_ID, UUID: 821763f8cd27aa29b90a86ef77bb794c
 *   CMD_DBG_TIMER_ID, UUID: ac7f67e633131cfd09d18498faaa66d0
 *   CMD_DBG_INTCNTRL_ID, UUID: d35af9493e8b7346f322651855961d21
 *   CMD_DBG_IPC_SPACES_ID, UUID: f89239963c881425d919527452eedcc7
 *   CMD_DBG_IPC_CHANNELS_ID, UUID: 47239853e10637d6ff8121e84fd692fd
 */
struct CMD_CORE_GENERIC {
  struct CMD_HDR parent;
  int32_t core;
} __attribute__((packed));

enum DbgHeapMode {
  DBG_HEAP_NONE = 0,
  DBG_HEAP_TRACE,
  DBG_HEAP_CRC_INFO,
  DBG_HEAP_CRC,
};

/**
 * Structure associated with the following commands:
 *
 *   CMD_DBG_HEAP_ID, UUID: 85e7278dbc868c35ff2c8a3dcc0d8447
 */
struct CMD_DBG_HEAP {
  struct CMD_CORE_GENERIC parent;
  uint32_t crc;
  uint8_t mode; /* For valid values, refer to "enum DbgHeapMode" */
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_RING_BIND_ID, UUID: 83c7fd9ba41a12ead4920ddbe02ce8fb
 */
struct CMD_RING_BIND {
  struct CMD_HDR parent;
  int32_t pin;
  uint16_t ipc_tag;
  uint32_t write_descr;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_IPC_NOTIF_ENABLE_ID, UUID: 4260b159455eaea220810438ee511c64
 */
struct CMD_IPC_NOTIF_ENABLE {
  struct CMD_HDR parent;
  uint32_t tag;
  uint8_t enable;
} __attribute__((packed));

#define CMD_SYS_VERSION_SIZE_MAX (64) /* UUID: 523a9f7b743ea29ea23a18c0879b0dcc */

/**
 * Structure associated with the following commands:
 *
 *   CMD_SYS_VERSION_GET_ID, UUID: a55b87f7dced9dc940f821514344afb0
 */
struct CMD_SYS_VERSION_GET {
  struct CMD_CORE_GENERIC parent;
  char version[CMD_SYS_VERSION_SIZE_MAX];
  char link_time[CMD_SYS_VERSION_SIZE_MAX];
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_SYS_STATS_TOT_ID, UUID: d3bacb0018cda42370e66d13020c60b8
 */
struct CMD_SYS_STATS_TOT {
  struct CMD_CORE_GENERIC parent;
  int32_t tot;
} __attribute__((packed));

enum STATS_TYPE {
  STATS_TYPE_TIMED_STATUS = 0,
  STATS_TYPE_DATA_TRANSFER,
};

#define STATS_ENTRY_LEN (7) /* UUID: 733b57b1d8a9342523a49b8c37ad2d0a */

struct STATS_ENTRY_INFO {
  char name[STATS_ENTRY_LEN];
  uint8_t type; /* For valid values, refer to "enum STATS_TYPE" */
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_SYS_STATS_INFO_GET_ID, UUID: a64551efd22e0590c51862fbdae982d0
 */
struct CMD_SYS_STATS_INFO_GET {
  struct CMD_CORE_GENERIC parent;
  int32_t index;
  struct STATS_ENTRY_INFO info;
} __attribute__((packed));

struct STATS_TIMED_STATUS {
  uint64_t counter;
  uint64_t cumulative_time;
  uint64_t timestamp_enter_last;
  uint64_t timestamp_exit_last;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_SYS_STATS_TIMED_GET_ID, UUID: d01577d896b1ce3c5406f93768bbccb4
 */
struct CMD_SYS_STATS_TIMED_GET {
  struct CMD_CORE_GENERIC parent;
  int32_t index;
  struct STATS_TIMED_STATUS timed;
} __attribute__((packed));

struct STATS_DATA_TRANSFER {
  uint64_t counter;
  uint64_t counter_failed;
  uint64_t transfer_tx;
  uint64_t transfer_rx;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_SYS_STATS_DATA_GET_ID, UUID: 2b508f8f52029e2f70505c9055ca50ce
 */
struct CMD_SYS_STATS_DATA_GET {
  struct CMD_CORE_GENERIC parent;
  int32_t index;
  struct STATS_DATA_TRANSFER transfer;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_SYS_LOGIC_TRACE_ENABLE_ID, UUID: 432fd371a0d5419f2d4e3e66f1b3f296
 *   CMD_DBG_TIMESTAMP_ID, UUID: a3776fb0d645d229eb361f7667ad22b2
 */
struct CMD_ENABLE {
  struct CMD_CORE_GENERIC parent;
  uint8_t enable;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_SYS_LOGIC_TRACE_SCHEME_SET_ID, UUID: 7188029a1fbb346bc53225b3afe5b030
 *   CMD_SYS_LOGIC_TRACE_SCHEME_GET_ID, UUID: fbb537085ace7493c9ee3208ceaf8bdb
 */
struct CMD_CORE_LOGIC_TRACE_SCHEME {
  struct CMD_CORE_GENERIC parent;
  int8_t scheme;
} __attribute__((packed));

#define EFWObject_kNameSize (16) /* UUID: 7488eddabe0654e3f0ac58cda17a1530 */

/**
 * Structure associated with the following commands:
 *
 *   CMD_DBG_INFO_ID, UUID: b68f8b693a8e2f56412d3c9fd0764f3f
 */
struct CMD_DBG_INFO {
  struct CMD_CORE_GENERIC parent;
  char string[EFWObject_kNameSize];
  uint8_t system;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_DBG_LEVEL_GET_ID, UUID: d9802e9e0e84b713e0efe86f3b2c7d29
 */
struct CMD_DBG_LEVEL_GET {
  struct CMD_CORE_GENERIC parent;
  char string[EFWObject_kNameSize];
  uint8_t system;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_DBG_POWERMAN_ID, UUID: 6636d2dceee1973b26d4033d28e5ff1c
 */
struct CMD_DBG_POWERMAN {
  struct CMD_CORE_GENERIC parent;
  uint8_t standby_modify;
  uint8_t standby_on;
  uint8_t retention_modify;
  uint8_t retention_on;
  uint8_t shutdown_modify;
  uint8_t shutdown_on;
  uint8_t status;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_DBG_LOG_ID, UUID: 84ed33f0d9a49a2e41bfc9f716205c0e
 */
struct CMD_DBG_LOG {
  struct CMD_CORE_GENERIC parent;
  uint8_t reset;
  uint8_t marker;
} __attribute__((packed));

enum DbgMemMode {
  DBG_MEM_MODE_32 = 0,
  DBG_MEM_MODE_16,
  DBG_MEM_MODE_8,
  DBG_MEM_MODE_RANGE,
};

/**
 * Structure associated with the following commands:
 *
 *   CMD_DBG_MEM_SET_ID, UUID: a0053bf6a498c6e83468ef77d59c669e
 */
struct CMD_DBG_MEM_SET {
  struct CMD_CORE_GENERIC parent;
  uint32_t address;
  uint32_t value;
  uint8_t mode; /* For valid values, refer to "enum DbgMemMode" */
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_DBG_MEM_DUMP_ID, UUID: 67540c4b228399c23f5f6b21a2e1a5aa
 */
struct CMD_DBG_MEM_DUMP {
  struct CMD_CORE_GENERIC parent;
  uint32_t address;
  uint32_t size;
} __attribute__((packed));

enum BTDecoderOutputIndex {
  BT_MODEM_OUTPUT_INDEX = 0,
  BT_AP_OUTPUT_INDEX,
  BT_HOTWORD_OUTPUT_INDEX,
  BT_DECODER_NUM_OUTPUTS,
};

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_INPUT_BT_DECODER_ENABLE_OUTPUT_ID, UUID: c3f9b1cfa15ea45ed2ef863dd5a41831
 */
struct CMD_AUDIO_INPUT_BT_ENABLE_OUTPUT {
  struct CMD_HDR parent;
  uint8_t output_index; /* For valid values, refer to "enum BTDecoderOutputIndex" */
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_INPUT_BT_DECODER_DISABLE_OUTPUT_ID, UUID: 63b67722fff716809497a40784905aee
 */
struct CMD_AUDIO_INPUT_BT_DISABLE_OUTPUT {
  struct CMD_HDR parent;
  uint8_t output_index; /* For valid values, refer to "enum BTDecoderOutputIndex" */
} __attribute__((packed));

enum InCallSelectOutputIndex {
  IN_CALL_SELECT_MODEM_IN_OUTPUT_INDEX = 0,
  IN_CALL_SELECT_MODEM_TX_OUTPUT_INDEX,
  IN_CALL_SELECT_NUM_OUTPUTS,
};

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_INPUT_IN_CALL_SELECT_ENABLE_OUTPUT_ID, UUID: f678fe0bfcf538552339b5523f39d238
 */
struct CMD_AUDIO_INPUT_IN_CALL_SELECT_ENABLE_OUTPUT {
  struct CMD_HDR parent;
  uint8_t output_index; /* For valid values, refer to "enum InCallSelectOutputIndex" */
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_INPUT_IN_CALL_SELECT_DISABLE_OUTPUT_ID, UUID: 31117c29d05a990add590eb09bbef831
 */
struct CMD_AUDIO_INPUT_IN_CALL_SELECT_DISABLE_OUTPUT {
  struct CMD_HDR parent;
  uint8_t output_index; /* For valid values, refer to "enum InCallSelectOutputIndex" */
} __attribute__((packed));

enum SampleRate {
  SR_8KHZ = 0,
  SR_16KHZ,
  SR_24KHZ,
  SR_32KHZ,
  SR_44K1HZ,
  SR_48KHZ,
  SR_96KHZ,
  SR_192KHZ,
};

enum Format {
  FRMT_FLOATING_POINT = 0,
  FRMT_FIXED_POINT,
};

enum BitsPerSample {
  WIDTH_8_BIT = 0,
  WIDTH_16_BIT,
  WIDTH_24_BIT,
  WIDTH_32_BIT,
};

enum Channels {
  CH_RESERVED = 0,
  CH_MONO,
  CH_STEREO,
  CH_3,
  CH_4,
  CH_5_1,
};

struct channelMetadataUnpacked {
  uint8_t chan; /* For valid values, refer to "enum Channels" */
  uint8_t bits; /* For valid values, refer to "enum BitsPerSample" */
  uint8_t sr; /* For valid values, refer to "enum SampleRate" */
  uint8_t format; /* For valid values, refer to "enum Format" */
  uint8_t offset;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_INPUT_MIC_RECORD_AP_SET_PARAMS_ID, UUID: 67a98c5287d71001e0e13510618255ef
 */
struct CMD_AUDIO_INPUT_MIC_RECORD_AP_SET_PARAMS {
  struct CMD_HDR parent;
  struct channelMetadataUnpacked requested_format;
  uint8_t pdm_mask;
  uint8_t period_ms;
  uint8_t num_periods;
  uint8_t sample_rate; /* For valid values, refer to "enum SampleRate" */
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_INPUT_MIC_LOOPBACK_START_ID, UUID: 711b1ae1da81a1b9df752984a6ec2116
 */
struct CMD_AUDIO_INPUT_ENABLE_MIC_LOOPBACK {
  struct CMD_HDR parent;
  uint8_t sample_rate; /* For valid values, refer to "enum SampleRate" */
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_INPUT_MIC_POWER_ON_ID, UUID: fddde5641c01e80c1842d9bb7a5ea267
 */
struct CMD_AUDIO_INPUT_MIC_POWER_ON {
  struct CMD_HDR parent;
  uint8_t mic_index;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_INPUT_MIC_POWER_OFF_ID, UUID: 2f970028559bc1857d7c6a9debde9103
 */
struct CMD_AUDIO_INPUT_MIC_POWER_OFF {
  struct CMD_HDR parent;
  uint8_t mic_index;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_INPUT_MIC_GET_POWER_STATE_ID, UUID: 68f073b8b729145c5c7231e6bcf0f3aa
 */
struct CMD_AUDIO_INPUT_MIC_GET_POWER_STATE {
  struct CMD_HDR parent;
  uint8_t mic_index;
  uint8_t power_state;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_SINK_ID, UUID: 2563958f8b4dfba075e8132404e71f4e
 */
struct CMD_AUDIO_OUTPUT_SINK {
  struct CMD_HDR parent;
  uint8_t sink;
  uint8_t on;
  uint8_t timestamping;
} __attribute__((packed));

enum EntrypointMode {
  ENTRYPOINT_MODE_OFF = 0,
  ENTRYPOINT_MODE_PLAYBACK,
  ENTRYPOINT_MODE_VOICE_TX,
  ENTRYPOINT_MODE_VOICE_RX,
  ENTRYPOINT_MODE_DECODE_OFFLOAD,
};

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_SOURCE_ID, UUID: 01d41bc9024d69cb02a9610c1a5a281b
 */
struct CMD_AUDIO_OUTPUT_SOURCE {
  struct CMD_HDR parent;
  uint8_t source;
  uint8_t mode; /* For valid values, refer to "enum EntrypointMode" */
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_BIND_ID, UUID: b73b5d0e3496b74cb42978a6ff2cda33
 */
struct CMD_AUDIO_OUTPUT_BIND {
  struct CMD_HDR parent;
  uint8_t src;
  uint8_t dst;
  uint8_t bind;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_WAV_PLAYBACK_ID, UUID: b9aed66214d53b02433a4cee8f08859a
 */
struct CMD_AUDIO_OUTPUT_WAV_PLAYBACK {
  struct CMD_HDR parent;
  uint8_t sink;
  uint8_t on;
  uint32_t address;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_GAIN_ID, UUID: 4988024210ec197e0505b2e72361cc43
 */
struct CMD_AUDIO_OUTPUT_GAIN {
  struct CMD_HDR parent;
  uint8_t sink;
  uint8_t channel;
  uint16_t gain;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_FX_EQ_ID, UUID: 042e5c11adb79a67aded9ca14665af80
 */
struct CMD_AUDIO_OUTPUT_FX_EQ {
  struct CMD_HDR parent;
  uint8_t sink;
  int8_t l;
  int8_t m;
  int8_t h;
} __attribute__((packed));

struct EntrypointDescriptorUnpacked {
  uint32_t address;
  uint32_t watermark;
  uint32_t length;
  struct channelMetadataUnpacked metadata;
  uint8_t channel;
  uint8_t wraparound;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_EP_SETUP_ID, UUID: 995a76aaa7daf0ca24f3cf5bcfcf563e
 */
struct CMD_AUDIO_OUTPUT_EP_SETUP {
  struct CMD_HDR parent;
  struct EntrypointDescriptorUnpacked d;
  uint8_t on;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_DECODE_ID, UUID: 5a055af87642f53d87a922a3deca0c94
 */
struct CMD_AUDIO_OUTPUT_DECODE {
  struct CMD_HDR parent;
  struct EntrypointDescriptorUnpacked raw_ep_descr;
  uint32_t address;
  int32_t size;
  uint8_t codec;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_AEC_NOTIFY_ID, UUID: 52bca856411b044e0f795bce53c5a89b
 */
struct CMD_AUDIO_OUTPUT_AEC_NOTIFY {
  struct CMD_HDR parent;
  int32_t index;
  uint8_t on;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_RESYNC_AUDIO_SINK_ID, UUID: 2ddce15ce0851ee038ebe709952c1d1b
 */
struct CMD_AUDIO_OUTPUT_RESYNC_AUDIO_SINK {
  struct CMD_HDR parent;
  uint8_t sink;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_GET_PARAMETER_ID, UUID: 41ab1e434bd41db920614eabd2c86e2f
 */
struct CMD_AUDIO_OUTPUT_GET_PARAMETER {
  struct CMD_HDR parent;
  uint8_t block;
  uint8_t component;
  uint32_t key;
  uint32_t val;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_GET_PARAMETER_BULK_ID, UUID: cf6494ca69bfbb7c3b1fcf2068250519
 */
struct CMD_AUDIO_OUTPUT_GET_PARAMETER_BULK {
  struct CMD_HDR parent;
  uint8_t block;
  uint8_t component;
  uint32_t rx_offset;
  uint32_t rx_address;
  uint32_t rx_size;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_SET_PARAMETER_ID, UUID: 1d86ba09f1c4868a6b0c65417dcf5970
 */
struct CMD_AUDIO_OUTPUT_SET_PARAMETER {
  struct CMD_HDR parent;
  uint8_t block;
  uint8_t component;
  uint32_t key;
  uint32_t val;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_SET_PARAMETER_BULK_ID, UUID: 3b59ff97b181270fc5017586eddf2263
 */
struct CMD_AUDIO_OUTPUT_SET_PARAMETER_BULK {
  struct CMD_HDR parent;
  uint8_t block;
  uint8_t component;
  uint32_t tx_offset;
  uint32_t tx_address;
  uint32_t tx_size;
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_SET_GET_PARAM_BULK_ID, UUID: bd5b731977550d9cd122eacb27f6c905
 */
struct CMD_AUDIO_OUTPUT_SET_GET_PARAM_BULK {
  struct CMD_HDR parent;
  uint8_t block;
  uint8_t component;
  uint16_t tx_offset;
  uint16_t rx_offset;
  uint32_t tx_address;
  uint32_t rx_address;
  uint16_t tx_size;
  uint16_t rx_size;
} __attribute__((packed));

enum HapticsMode {
  HAPTICS_MODE_OFF = 0,
  HAPTICS_MODE_PCM,
  HAPTICS_MODE_FX,
};

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_CFG_HAPTICS_ID, UUID: 2c80ea0d2eda17e2cadee0ab54e78187
 */
struct CMD_AUDIO_OUTPUT_CFG_HAPTICS {
  struct CMD_HDR parent;
  uint8_t mode; /* For valid values, refer to "enum HapticsMode" */
} __attribute__((packed));

/**
 * Structure associated with the following commands:
 *
 *   CMD_AUDIO_OUTPUT_CFG_SIGGEN_ID, UUID: 34f07e1c9969ebafa4d4028d68c8bed7
 */
struct CMD_AUDIO_OUTPUT_CFG_SIGGEN {
  struct CMD_HDR parent;
  uint8_t wf_type;
  uint16_t wf_period;
  uint32_t wf_amplitude;
} __attribute__((packed));

struct NOTIF_HDR {
  struct CONTAINER_HDR parent;
  uint32_t id;
  uint32_t tag;
} __attribute__((packed));

#define notif_payload (36) /* UUID: 21377ce718fd3e9bec883f8fb476c056 */

/**
 * Structure associated with the following notifications:
 *
 *   NOTIF_AUDIO_INPUT_AP_MIC_RECORD_DATA_AVAILABLE_ID, UUID: 29ff3e76c33148ccdfd493c21f77f8b3
 */
struct NOTIF {
  struct NOTIF_HDR parent;
  uint8_t payload[notif_payload];
} __attribute__((packed));



/**
 * Helper function to initialize commands
 *
 * \param[out] cmd Pointer to command structure to initialize
 * \param[in] id Command ID.  Refer to \ref AOC_COMMAND
 * \param[in] length Command length (size of the command structure)
 */
static inline void AocCmdHdrSet(struct CMD_HDR * cmd, uint16_t id, uint16_t length) {
  static uint8_t cmd_cntr_ = 0;

  cmd->parent.type = DATA_TYPE_CMD;
  cmd->parent.cntr = cmd_cntr_++;
  cmd->parent.len = length;
  cmd->id = id;
}


/**
 * Total number of UUID strings to check against the FW image.
 */
#define AOC_UUID_ENTRIES (81)

/**
 * UUID entry size.
 */
#define AOC_UUID_SIZE (16)


/**
 * Function to check interface compatibility
 *
 * \param[in] addr UUID table's address
 * \param[in] size UUID table's size
 *
 * \return 0 if compatibility is Ok, -1 otherwise
 */
inline int AocInterfaceCheck(const void * addr, int size) {
  static const uint8_t uuid_array[AOC_UUID_ENTRIES][AOC_UUID_SIZE] = { 
      { 0x01, 0xd4, 0x1b, 0xc9, 0x02, 0x4d, 0x69, 0xcb, 0x02, 0xa9, 0x61, 0x0c, 0x1a, 0x5a, 0x28, 0x1b},
      { 0x04, 0x2e, 0x5c, 0x11, 0xad, 0xb7, 0x9a, 0x67, 0xad, 0xed, 0x9c, 0xa1, 0x46, 0x65, 0xaf, 0x80},
      { 0x11, 0xbc, 0xb4, 0x86, 0xe7, 0xe1, 0x22, 0x41, 0xb0, 0x39, 0x6d, 0x6c, 0x66, 0xca, 0xf4, 0x2d},
      { 0x18, 0xfd, 0xab, 0x46, 0x30, 0x1e, 0x62, 0x25, 0x74, 0xda, 0x7e, 0xbf, 0x4c, 0xcc, 0x46, 0x63},
      { 0x1d, 0x86, 0xba, 0x09, 0xf1, 0xc4, 0x86, 0x8a, 0x6b, 0x0c, 0x65, 0x41, 0x7d, 0xcf, 0x59, 0x70},
      { 0x21, 0x37, 0x7c, 0xe7, 0x18, 0xfd, 0x3e, 0x9b, 0xec, 0x88, 0x3f, 0x8f, 0xb4, 0x76, 0xc0, 0x56},
      { 0x25, 0x63, 0x95, 0x8f, 0x8b, 0x4d, 0xfb, 0xa0, 0x75, 0xe8, 0x13, 0x24, 0x04, 0xe7, 0x1f, 0x4e},
      { 0x26, 0xff, 0x9e, 0x04, 0x4e, 0x65, 0x51, 0x07, 0x75, 0x29, 0x1a, 0xbe, 0x87, 0x40, 0x5f, 0xbc},
      { 0x29, 0xff, 0x3e, 0x76, 0xc3, 0x31, 0x48, 0xcc, 0xdf, 0xd4, 0x93, 0xc2, 0x1f, 0x77, 0xf8, 0xb3},
      { 0x2b, 0x50, 0x8f, 0x8f, 0x52, 0x02, 0x9e, 0x2f, 0x70, 0x50, 0x5c, 0x90, 0x55, 0xca, 0x50, 0xce},
      { 0x2c, 0x80, 0xea, 0x0d, 0x2e, 0xda, 0x17, 0xe2, 0xca, 0xde, 0xe0, 0xab, 0x54, 0xe7, 0x81, 0x87},
      { 0x2d, 0xdc, 0xe1, 0x5c, 0xe0, 0x85, 0x1e, 0xe0, 0x38, 0xeb, 0xe7, 0x09, 0x95, 0x2c, 0x1d, 0x1b},
      { 0x2f, 0x97, 0x00, 0x28, 0x55, 0x9b, 0xc1, 0x85, 0x7d, 0x7c, 0x6a, 0x9d, 0xeb, 0xde, 0x91, 0x03},
      { 0x2f, 0xad, 0x4c, 0xb4, 0x75, 0xc4, 0x96, 0xc9, 0xf7, 0x6c, 0x32, 0xdc, 0xa4, 0xc0, 0x13, 0x6a},
      { 0x31, 0x11, 0x7c, 0x29, 0xd0, 0x5a, 0x99, 0x0a, 0xdd, 0x59, 0x0e, 0xb0, 0x9b, 0xbe, 0xf8, 0x31},
      { 0x34, 0xf0, 0x7e, 0x1c, 0x99, 0x69, 0xeb, 0xaf, 0xa4, 0xd4, 0x02, 0x8d, 0x68, 0xc8, 0xbe, 0xd7},
      { 0x38, 0x60, 0x6b, 0xfc, 0x60, 0x7b, 0x5b, 0xf1, 0xa2, 0x16, 0xca, 0x12, 0x77, 0xff, 0x73, 0x8f},
      { 0x3b, 0x59, 0xff, 0x97, 0xb1, 0x81, 0x27, 0x0f, 0xc5, 0x01, 0x75, 0x86, 0xed, 0xdf, 0x22, 0x63},
      { 0x3e, 0x92, 0xcd, 0x4c, 0xb4, 0xcd, 0xb8, 0x6f, 0x8e, 0x08, 0x16, 0x05, 0x4b, 0xf0, 0x5a, 0xd9},
      { 0x41, 0xa3, 0xb7, 0x89, 0x94, 0x91, 0xb1, 0x9c, 0x0d, 0x32, 0x89, 0x93, 0x70, 0x5a, 0xed, 0xe1},
      { 0x41, 0xab, 0x1e, 0x43, 0x4b, 0xd4, 0x1d, 0xb9, 0x20, 0x61, 0x4e, 0xab, 0xd2, 0xc8, 0x6e, 0x2f},
      { 0x42, 0x60, 0xb1, 0x59, 0x45, 0x5e, 0xae, 0xa2, 0x20, 0x81, 0x04, 0x38, 0xee, 0x51, 0x1c, 0x64},
      { 0x43, 0x2f, 0xd3, 0x71, 0xa0, 0xd5, 0x41, 0x9f, 0x2d, 0x4e, 0x3e, 0x66, 0xf1, 0xb3, 0xf2, 0x96},
      { 0x44, 0x87, 0x9f, 0xb7, 0x90, 0x1d, 0x85, 0x70, 0x99, 0x35, 0x14, 0xa3, 0x8d, 0x79, 0x0e, 0x35},
      { 0x47, 0x23, 0x98, 0x53, 0xe1, 0x06, 0x37, 0xd6, 0xff, 0x81, 0x21, 0xe8, 0x4f, 0xd6, 0x92, 0xfd},
      { 0x49, 0x88, 0x02, 0x42, 0x10, 0xec, 0x19, 0x7e, 0x05, 0x05, 0xb2, 0xe7, 0x23, 0x61, 0xcc, 0x43},
      { 0x52, 0x3a, 0x9f, 0x7b, 0x74, 0x3e, 0xa2, 0x9e, 0xa2, 0x3a, 0x18, 0xc0, 0x87, 0x9b, 0x0d, 0xcc},
      { 0x52, 0xbc, 0xa8, 0x56, 0x41, 0x1b, 0x04, 0x4e, 0x0f, 0x79, 0x5b, 0xce, 0x53, 0xc5, 0xa8, 0x9b},
      { 0x53, 0xf2, 0xef, 0xdb, 0x44, 0xaf, 0x39, 0xdf, 0x1b, 0x32, 0x42, 0x60, 0x0b, 0x9c, 0x82, 0x02},
      { 0x57, 0x71, 0x74, 0xa2, 0xce, 0x33, 0x3a, 0x46, 0xf6, 0x8e, 0x04, 0x47, 0x0c, 0xcb, 0xb9, 0x67},
      { 0x5a, 0x05, 0x5a, 0xf8, 0x76, 0x42, 0xf5, 0x3d, 0x87, 0xa9, 0x22, 0xa3, 0xde, 0xca, 0x0c, 0x94},
      { 0x5c, 0xc6, 0x9d, 0xf1, 0x2d, 0x2f, 0xe9, 0x60, 0x74, 0xe0, 0xbf, 0x7f, 0x4a, 0xf6, 0x53, 0xc9},
      { 0x63, 0xb6, 0x77, 0x22, 0xff, 0xf7, 0x16, 0x80, 0x94, 0x97, 0xa4, 0x07, 0x84, 0x90, 0x5a, 0xee},
      { 0x63, 0xcb, 0x8f, 0x09, 0x24, 0x94, 0xb9, 0x57, 0xfc, 0xd9, 0x30, 0x39, 0xd9, 0x04, 0x61, 0x3f},
      { 0x66, 0x36, 0xd2, 0xdc, 0xee, 0xe1, 0x97, 0x3b, 0x26, 0xd4, 0x03, 0x3d, 0x28, 0xe5, 0xff, 0x1c},
      { 0x67, 0x54, 0x0c, 0x4b, 0x22, 0x83, 0x99, 0xc2, 0x3f, 0x5f, 0x6b, 0x21, 0xa2, 0xe1, 0xa5, 0xaa},
      { 0x67, 0xa9, 0x8c, 0x52, 0x87, 0xd7, 0x10, 0x01, 0xe0, 0xe1, 0x35, 0x10, 0x61, 0x82, 0x55, 0xef},
      { 0x68, 0xf0, 0x73, 0xb8, 0xb7, 0x29, 0x14, 0x5c, 0x5c, 0x72, 0x31, 0xe6, 0xbc, 0xf0, 0xf3, 0xaa},
      { 0x6d, 0xaf, 0xca, 0x1b, 0x50, 0xff, 0x4f, 0x7a, 0xac, 0xc4, 0x00, 0x6c, 0x0e, 0x10, 0x4b, 0x7e},
      { 0x6f, 0xf8, 0xa9, 0xe0, 0x24, 0x99, 0x04, 0xd2, 0x05, 0x9b, 0xb0, 0x69, 0xdf, 0xcd, 0x53, 0x57},
      { 0x71, 0x1b, 0x1a, 0xe1, 0xda, 0x81, 0xa1, 0xb9, 0xdf, 0x75, 0x29, 0x84, 0xa6, 0xec, 0x21, 0x16},
      { 0x71, 0x88, 0x02, 0x9a, 0x1f, 0xbb, 0x34, 0x6b, 0xc5, 0x32, 0x25, 0xb3, 0xaf, 0xe5, 0xb0, 0x30},
      { 0x71, 0xbc, 0x54, 0x8e, 0x4d, 0x11, 0x01, 0x6c, 0x86, 0xef, 0x26, 0x7c, 0x16, 0xa1, 0x61, 0xd9},
      { 0x72, 0x7c, 0x13, 0xb0, 0xf2, 0x0d, 0x95, 0x57, 0xa6, 0x6e, 0x2c, 0x58, 0x11, 0x3d, 0xfc, 0xf4},
      { 0x73, 0x3b, 0x57, 0xb1, 0xd8, 0xa9, 0x34, 0x25, 0x23, 0xa4, 0x9b, 0x8c, 0x37, 0xad, 0x2d, 0x0a},
      { 0x74, 0x88, 0xed, 0xda, 0xbe, 0x06, 0x54, 0xe3, 0xf0, 0xac, 0x58, 0xcd, 0xa1, 0x7a, 0x15, 0x30},
      { 0x7b, 0x90, 0x75, 0xe0, 0x31, 0x8e, 0xba, 0x31, 0x4f, 0x60, 0xf6, 0x2f, 0xe5, 0x3c, 0xda, 0x03},
      { 0x7f, 0x37, 0x83, 0xae, 0xdb, 0xae, 0x03, 0x85, 0x4d, 0x3c, 0xb2, 0x85, 0x1a, 0xa0, 0x7b, 0x40},
      { 0x82, 0x17, 0x63, 0xf8, 0xcd, 0x27, 0xaa, 0x29, 0xb9, 0x0a, 0x86, 0xef, 0x77, 0xbb, 0x79, 0x4c},
      { 0x83, 0xc7, 0xfd, 0x9b, 0xa4, 0x1a, 0x12, 0xea, 0xd4, 0x92, 0x0d, 0xdb, 0xe0, 0x2c, 0xe8, 0xfb},
      { 0x84, 0xed, 0x33, 0xf0, 0xd9, 0xa4, 0x9a, 0x2e, 0x41, 0xbf, 0xc9, 0xf7, 0x16, 0x20, 0x5c, 0x0e},
      { 0x85, 0xe7, 0x27, 0x8d, 0xbc, 0x86, 0x8c, 0x35, 0xff, 0x2c, 0x8a, 0x3d, 0xcc, 0x0d, 0x84, 0x47},
      { 0x99, 0x5a, 0x76, 0xaa, 0xa7, 0xda, 0xf0, 0xca, 0x24, 0xf3, 0xcf, 0x5b, 0xcf, 0xcf, 0x56, 0x3e},
      { 0xa0, 0x05, 0x3b, 0xf6, 0xa4, 0x98, 0xc6, 0xe8, 0x34, 0x68, 0xef, 0x77, 0xd5, 0x9c, 0x66, 0x9e},
      { 0xa3, 0x77, 0x6f, 0xb0, 0xd6, 0x45, 0xd2, 0x29, 0xeb, 0x36, 0x1f, 0x76, 0x67, 0xad, 0x22, 0xb2},
      { 0xa5, 0x5b, 0x87, 0xf7, 0xdc, 0xed, 0x9d, 0xc9, 0x40, 0xf8, 0x21, 0x51, 0x43, 0x44, 0xaf, 0xb0},
      { 0xa6, 0x45, 0x51, 0xef, 0xd2, 0x2e, 0x05, 0x90, 0xc5, 0x18, 0x62, 0xfb, 0xda, 0xe9, 0x82, 0xd0},
      { 0xaa, 0xf5, 0x47, 0x9b, 0x1b, 0xe9, 0x8e, 0x8b, 0x7c, 0x8d, 0xf2, 0x2f, 0xe2, 0xf5, 0x76, 0xde},
      { 0xac, 0x7f, 0x67, 0xe6, 0x33, 0x13, 0x1c, 0xfd, 0x09, 0xd1, 0x84, 0x98, 0xfa, 0xaa, 0x66, 0xd0},
      { 0xb0, 0x82, 0xcb, 0xc3, 0xdd, 0x47, 0xaf, 0xfc, 0xbe, 0xd8, 0x1f, 0x2f, 0x6a, 0x8b, 0xdc, 0x26},
      { 0xb6, 0x8f, 0x8b, 0x69, 0x3a, 0x8e, 0x2f, 0x56, 0x41, 0x2d, 0x3c, 0x9f, 0xd0, 0x76, 0x4f, 0x3f},
      { 0xb7, 0x3b, 0x5d, 0x0e, 0x34, 0x96, 0xb7, 0x4c, 0xb4, 0x29, 0x78, 0xa6, 0xff, 0x2c, 0xda, 0x33},
      { 0xb9, 0xae, 0xd6, 0x62, 0x14, 0xd5, 0x3b, 0x02, 0x43, 0x3a, 0x4c, 0xee, 0x8f, 0x08, 0x85, 0x9a},
      { 0xbd, 0x5b, 0x73, 0x19, 0x77, 0x55, 0x0d, 0x9c, 0xd1, 0x22, 0xea, 0xcb, 0x27, 0xf6, 0xc9, 0x05},
      { 0xbe, 0x65, 0x0f, 0xd5, 0xee, 0x17, 0x04, 0x46, 0x03, 0xde, 0xb3, 0x65, 0x08, 0x0f, 0x5e, 0xad},
      { 0xc3, 0xf9, 0xb1, 0xcf, 0xa1, 0x5e, 0xa4, 0x5e, 0xd2, 0xef, 0x86, 0x3d, 0xd5, 0xa4, 0x18, 0x31},
      { 0xcf, 0x64, 0x94, 0xca, 0x69, 0xbf, 0xbb, 0x7c, 0x3b, 0x1f, 0xcf, 0x20, 0x68, 0x25, 0x05, 0x19},
      { 0xd0, 0x15, 0x77, 0xd8, 0x96, 0xb1, 0xce, 0x3c, 0x54, 0x06, 0xf9, 0x37, 0x68, 0xbb, 0xcc, 0xb4},
      { 0xd1, 0xc9, 0x58, 0x02, 0x7b, 0x2e, 0xd6, 0xf8, 0xa4, 0xbf, 0xab, 0x4e, 0x29, 0xde, 0xb0, 0x1f},
      { 0xd3, 0x5a, 0xf9, 0x49, 0x3e, 0x8b, 0x73, 0x46, 0xf3, 0x22, 0x65, 0x18, 0x55, 0x96, 0x1d, 0x21},
      { 0xd3, 0xa5, 0x2c, 0xad, 0x71, 0x78, 0x26, 0x91, 0x8f, 0x48, 0x4e, 0xf6, 0x48, 0x74, 0xd1, 0x81},
      { 0xd3, 0xba, 0xcb, 0x00, 0x18, 0xcd, 0xa4, 0x23, 0x70, 0xe6, 0x6d, 0x13, 0x02, 0x0c, 0x60, 0xb8},
      { 0xd9, 0x80, 0x2e, 0x9e, 0x0e, 0x84, 0xb7, 0x13, 0xe0, 0xef, 0xe8, 0x6f, 0x3b, 0x2c, 0x7d, 0x29},
      { 0xda, 0x94, 0x9c, 0x27, 0xa8, 0xbc, 0x2d, 0xc7, 0x85, 0x65, 0x5f, 0x91, 0x07, 0x5a, 0xca, 0x1a},
      { 0xe4, 0x0c, 0x41, 0x52, 0xfc, 0xde, 0x65, 0xb6, 0x66, 0x3f, 0x1c, 0x58, 0xb8, 0x7f, 0x26, 0x78},
      { 0xee, 0x98, 0x47, 0xde, 0x96, 0xd9, 0x39, 0xcf, 0x40, 0x76, 0x16, 0xdb, 0x9e, 0xd0, 0x2d, 0x35},
      { 0xf6, 0x78, 0xfe, 0x0b, 0xfc, 0xf5, 0x38, 0x55, 0x23, 0x39, 0xb5, 0x52, 0x3f, 0x39, 0xd2, 0x38},
      { 0xf7, 0xd9, 0xf1, 0x72, 0x24, 0x7f, 0xe1, 0x27, 0xaf, 0x59, 0x86, 0xed, 0x9d, 0x9c, 0x35, 0x86},
      { 0xf8, 0x92, 0x39, 0x96, 0x3c, 0x88, 0x14, 0x25, 0xd9, 0x19, 0x52, 0x74, 0x52, 0xee, 0xdc, 0xc7},
      { 0xfb, 0xb5, 0x37, 0x08, 0x5a, 0xce, 0x74, 0x93, 0xc9, 0xee, 0x32, 0x08, 0xce, 0xaf, 0x8b, 0xdb},
      { 0xfd, 0xdd, 0xe5, 0x64, 0x1c, 0x01, 0xe8, 0x0c, 0x18, 0x42, 0xd9, 0xbb, 0x7a, 0x5e, 0xa2, 0x67},
    };
  int start = 0;
  int last = size / AOC_UUID_SIZE;
  int entry;
  int rc = 0;

  /*
   * The UUIDs entries are sorted therefore moving the start of the
   * inner loop is enough to minimize the search checks
   */

  for (entry = 0; entry < AOC_UUID_ENTRIES; entry++) {
    const uint8_t * uuid = &(uuid_array[entry][0]);
    int index;

    rc = -1;

    for (index = start; index < last; index += 1) {
      const uint8_t * ptr;
      int j;

      ptr = &(((const uint8_t *)addr)[index * AOC_UUID_SIZE]);

      for (j = 0; j < AOC_UUID_SIZE; j++) {
        if (uuid[j] != ptr[j]) {
          break;
        }
      }
      if (j == AOC_UUID_SIZE) {
        if (index == start) {
          start += 1;
        }
        rc = 0;
        break;
      }
    }
    if (index == last) {
      rc = -1;
      break;
    }
  }
  return rc;
}


#endif /* AOC_INTERFACE_H_ */

